// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tsai.eu/solar/controller/solar.proto

package main

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VoidMessage struct {
	Version              string   `protobuf:"bytes,1,opt,name=Version,proto3" json:"Version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoidMessage) Reset()         { *m = VoidMessage{} }
func (m *VoidMessage) String() string { return proto.CompactTextString(m) }
func (*VoidMessage) ProtoMessage()    {}
func (*VoidMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_304cfb64bcde0875, []int{0}
}

func (m *VoidMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoidMessage.Unmarshal(m, b)
}
func (m *VoidMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoidMessage.Marshal(b, m, deterministic)
}
func (m *VoidMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoidMessage.Merge(m, src)
}
func (m *VoidMessage) XXX_Size() int {
	return xxx_messageInfo_VoidMessage.Size(m)
}
func (m *VoidMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_VoidMessage.DiscardUnknown(m)
}

var xxx_messageInfo_VoidMessage proto.InternalMessageInfo

func (m *VoidMessage) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type InstanceSetupMessage struct {
	Instance                string   `protobuf:"bytes,1,opt,name=Instance,proto3" json:"Instance,omitempty"`
	Target                  string   `protobuf:"bytes,2,opt,name=Target,proto3" json:"Target,omitempty"`
	State                   string   `protobuf:"bytes,3,opt,name=State,proto3" json:"State,omitempty"`
	BaseConfiguration       string   `protobuf:"bytes,4,opt,name=BaseConfiguration,proto3" json:"BaseConfiguration,omitempty"`
	DesignTimeConfiguration string   `protobuf:"bytes,5,opt,name=DesignTimeConfiguration,proto3" json:"DesignTimeConfiguration,omitempty"`
	RuntimeConfiguration    string   `protobuf:"bytes,6,opt,name=RuntimeConfiguration,proto3" json:"RuntimeConfiguration,omitempty"`
	Endpoint                string   `protobuf:"bytes,7,opt,name=Endpoint,proto3" json:"Endpoint,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *InstanceSetupMessage) Reset()         { *m = InstanceSetupMessage{} }
func (m *InstanceSetupMessage) String() string { return proto.CompactTextString(m) }
func (*InstanceSetupMessage) ProtoMessage()    {}
func (*InstanceSetupMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_304cfb64bcde0875, []int{1}
}

func (m *InstanceSetupMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceSetupMessage.Unmarshal(m, b)
}
func (m *InstanceSetupMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceSetupMessage.Marshal(b, m, deterministic)
}
func (m *InstanceSetupMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceSetupMessage.Merge(m, src)
}
func (m *InstanceSetupMessage) XXX_Size() int {
	return xxx_messageInfo_InstanceSetupMessage.Size(m)
}
func (m *InstanceSetupMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceSetupMessage.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceSetupMessage proto.InternalMessageInfo

func (m *InstanceSetupMessage) GetInstance() string {
	if m != nil {
		return m.Instance
	}
	return ""
}

func (m *InstanceSetupMessage) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *InstanceSetupMessage) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *InstanceSetupMessage) GetBaseConfiguration() string {
	if m != nil {
		return m.BaseConfiguration
	}
	return ""
}

func (m *InstanceSetupMessage) GetDesignTimeConfiguration() string {
	if m != nil {
		return m.DesignTimeConfiguration
	}
	return ""
}

func (m *InstanceSetupMessage) GetRuntimeConfiguration() string {
	if m != nil {
		return m.RuntimeConfiguration
	}
	return ""
}

func (m *InstanceSetupMessage) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

type RelationshipSetupMessage struct {
	Relationship            string   `protobuf:"bytes,1,opt,name=Relationship,proto3" json:"Relationship,omitempty"`
	Element                 string   `protobuf:"bytes,2,opt,name=Element,proto3" json:"Element,omitempty"`
	Version                 string   `protobuf:"bytes,3,opt,name=Version,proto3" json:"Version,omitempty"`
	Target                  string   `protobuf:"bytes,4,opt,name=Target,proto3" json:"Target,omitempty"`
	State                   string   `protobuf:"bytes,5,opt,name=State,proto3" json:"State,omitempty"`
	BaseConfiguration       string   `protobuf:"bytes,6,opt,name=BaseConfiguration,proto3" json:"BaseConfiguration,omitempty"`
	DesignTimeConfiguration string   `protobuf:"bytes,7,opt,name=DesignTimeConfiguration,proto3" json:"DesignTimeConfiguration,omitempty"`
	RuntimeConfiguration    string   `protobuf:"bytes,8,opt,name=RuntimeConfiguration,proto3" json:"RuntimeConfiguration,omitempty"`
	Endpoint                string   `protobuf:"bytes,9,opt,name=Endpoint,proto3" json:"Endpoint,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *RelationshipSetupMessage) Reset()         { *m = RelationshipSetupMessage{} }
func (m *RelationshipSetupMessage) String() string { return proto.CompactTextString(m) }
func (*RelationshipSetupMessage) ProtoMessage()    {}
func (*RelationshipSetupMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_304cfb64bcde0875, []int{2}
}

func (m *RelationshipSetupMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelationshipSetupMessage.Unmarshal(m, b)
}
func (m *RelationshipSetupMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelationshipSetupMessage.Marshal(b, m, deterministic)
}
func (m *RelationshipSetupMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelationshipSetupMessage.Merge(m, src)
}
func (m *RelationshipSetupMessage) XXX_Size() int {
	return xxx_messageInfo_RelationshipSetupMessage.Size(m)
}
func (m *RelationshipSetupMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RelationshipSetupMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RelationshipSetupMessage proto.InternalMessageInfo

func (m *RelationshipSetupMessage) GetRelationship() string {
	if m != nil {
		return m.Relationship
	}
	return ""
}

func (m *RelationshipSetupMessage) GetElement() string {
	if m != nil {
		return m.Element
	}
	return ""
}

func (m *RelationshipSetupMessage) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *RelationshipSetupMessage) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *RelationshipSetupMessage) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *RelationshipSetupMessage) GetBaseConfiguration() string {
	if m != nil {
		return m.BaseConfiguration
	}
	return ""
}

func (m *RelationshipSetupMessage) GetDesignTimeConfiguration() string {
	if m != nil {
		return m.DesignTimeConfiguration
	}
	return ""
}

func (m *RelationshipSetupMessage) GetRuntimeConfiguration() string {
	if m != nil {
		return m.RuntimeConfiguration
	}
	return ""
}

func (m *RelationshipSetupMessage) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

type ClusterSetupMessage struct {
	Cluster                 string                               `protobuf:"bytes,1,opt,name=Cluster,proto3" json:"Cluster,omitempty"`
	Target                  string                               `protobuf:"bytes,2,opt,name=Target,proto3" json:"Target,omitempty"`
	State                   string                               `protobuf:"bytes,3,opt,name=State,proto3" json:"State,omitempty"`
	Min                     int64                                `protobuf:"varint,4,opt,name=Min,proto3" json:"Min,omitempty"`
	Max                     int64                                `protobuf:"varint,5,opt,name=Max,proto3" json:"Max,omitempty"`
	Size                    int64                                `protobuf:"varint,6,opt,name=Size,proto3" json:"Size,omitempty"`
	BaseConfiguration       string                               `protobuf:"bytes,7,opt,name=BaseConfiguration,proto3" json:"BaseConfiguration,omitempty"`
	DesignTimeConfiguration string                               `protobuf:"bytes,8,opt,name=DesignTimeConfiguration,proto3" json:"DesignTimeConfiguration,omitempty"`
	RuntimeConfiguration    string                               `protobuf:"bytes,9,opt,name=RuntimeConfiguration,proto3" json:"RuntimeConfiguration,omitempty"`
	Endpoint                string                               `protobuf:"bytes,10,opt,name=Endpoint,proto3" json:"Endpoint,omitempty"`
	Relationships           map[string]*RelationshipSetupMessage `protobuf:"bytes,11,rep,name=Relationships,proto3" json:"Relationships,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Instances               map[string]*InstanceSetupMessage     `protobuf:"bytes,12,rep,name=Instances,proto3" json:"Instances,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral    struct{}                             `json:"-"`
	XXX_unrecognized        []byte                               `json:"-"`
	XXX_sizecache           int32                                `json:"-"`
}

func (m *ClusterSetupMessage) Reset()         { *m = ClusterSetupMessage{} }
func (m *ClusterSetupMessage) String() string { return proto.CompactTextString(m) }
func (*ClusterSetupMessage) ProtoMessage()    {}
func (*ClusterSetupMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_304cfb64bcde0875, []int{3}
}

func (m *ClusterSetupMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterSetupMessage.Unmarshal(m, b)
}
func (m *ClusterSetupMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterSetupMessage.Marshal(b, m, deterministic)
}
func (m *ClusterSetupMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterSetupMessage.Merge(m, src)
}
func (m *ClusterSetupMessage) XXX_Size() int {
	return xxx_messageInfo_ClusterSetupMessage.Size(m)
}
func (m *ClusterSetupMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterSetupMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterSetupMessage proto.InternalMessageInfo

func (m *ClusterSetupMessage) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *ClusterSetupMessage) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *ClusterSetupMessage) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *ClusterSetupMessage) GetMin() int64 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *ClusterSetupMessage) GetMax() int64 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *ClusterSetupMessage) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ClusterSetupMessage) GetBaseConfiguration() string {
	if m != nil {
		return m.BaseConfiguration
	}
	return ""
}

func (m *ClusterSetupMessage) GetDesignTimeConfiguration() string {
	if m != nil {
		return m.DesignTimeConfiguration
	}
	return ""
}

func (m *ClusterSetupMessage) GetRuntimeConfiguration() string {
	if m != nil {
		return m.RuntimeConfiguration
	}
	return ""
}

func (m *ClusterSetupMessage) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *ClusterSetupMessage) GetRelationships() map[string]*RelationshipSetupMessage {
	if m != nil {
		return m.Relationships
	}
	return nil
}

func (m *ClusterSetupMessage) GetInstances() map[string]*InstanceSetupMessage {
	if m != nil {
		return m.Instances
	}
	return nil
}

type ElementSetupMessage struct {
	Element                 string                          `protobuf:"bytes,1,opt,name=Element,proto3" json:"Element,omitempty"`
	Component               string                          `protobuf:"bytes,2,opt,name=Component,proto3" json:"Component,omitempty"`
	Target                  string                          `protobuf:"bytes,3,opt,name=Target,proto3" json:"Target,omitempty"`
	State                   string                          `protobuf:"bytes,4,opt,name=State,proto3" json:"State,omitempty"`
	DesignTimeConfiguration string                          `protobuf:"bytes,5,opt,name=DesignTimeConfiguration,proto3" json:"DesignTimeConfiguration,omitempty"`
	RuntimeConfiguration    string                          `protobuf:"bytes,6,opt,name=RuntimeConfiguration,proto3" json:"RuntimeConfiguration,omitempty"`
	Endpoint                string                          `protobuf:"bytes,7,opt,name=Endpoint,proto3" json:"Endpoint,omitempty"`
	Clusters                map[string]*ClusterSetupMessage `protobuf:"bytes,8,rep,name=Clusters,proto3" json:"Clusters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral    struct{}                        `json:"-"`
	XXX_unrecognized        []byte                          `json:"-"`
	XXX_sizecache           int32                           `json:"-"`
}

func (m *ElementSetupMessage) Reset()         { *m = ElementSetupMessage{} }
func (m *ElementSetupMessage) String() string { return proto.CompactTextString(m) }
func (*ElementSetupMessage) ProtoMessage()    {}
func (*ElementSetupMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_304cfb64bcde0875, []int{4}
}

func (m *ElementSetupMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ElementSetupMessage.Unmarshal(m, b)
}
func (m *ElementSetupMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ElementSetupMessage.Marshal(b, m, deterministic)
}
func (m *ElementSetupMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ElementSetupMessage.Merge(m, src)
}
func (m *ElementSetupMessage) XXX_Size() int {
	return xxx_messageInfo_ElementSetupMessage.Size(m)
}
func (m *ElementSetupMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ElementSetupMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ElementSetupMessage proto.InternalMessageInfo

func (m *ElementSetupMessage) GetElement() string {
	if m != nil {
		return m.Element
	}
	return ""
}

func (m *ElementSetupMessage) GetComponent() string {
	if m != nil {
		return m.Component
	}
	return ""
}

func (m *ElementSetupMessage) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *ElementSetupMessage) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *ElementSetupMessage) GetDesignTimeConfiguration() string {
	if m != nil {
		return m.DesignTimeConfiguration
	}
	return ""
}

func (m *ElementSetupMessage) GetRuntimeConfiguration() string {
	if m != nil {
		return m.RuntimeConfiguration
	}
	return ""
}

func (m *ElementSetupMessage) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *ElementSetupMessage) GetClusters() map[string]*ClusterSetupMessage {
	if m != nil {
		return m.Clusters
	}
	return nil
}

type SetupMessage struct {
	Domain                  string                          `protobuf:"bytes,1,opt,name=Domain,proto3" json:"Domain,omitempty"`
	Solution                string                          `protobuf:"bytes,2,opt,name=Solution,proto3" json:"Solution,omitempty"`
	Version                 string                          `protobuf:"bytes,3,opt,name=Version,proto3" json:"Version,omitempty"`
	Element                 string                          `protobuf:"bytes,4,opt,name=Element,proto3" json:"Element,omitempty"`
	Cluster                 string                          `protobuf:"bytes,5,opt,name=Cluster,proto3" json:"Cluster,omitempty"`
	Instance                string                          `protobuf:"bytes,6,opt,name=Instance,proto3" json:"Instance,omitempty"`
	Target                  string                          `protobuf:"bytes,7,opt,name=Target,proto3" json:"Target,omitempty"`
	State                   string                          `protobuf:"bytes,8,opt,name=State,proto3" json:"State,omitempty"`
	DesignTimeConfiguration string                          `protobuf:"bytes,9,opt,name=DesignTimeConfiguration,proto3" json:"DesignTimeConfiguration,omitempty"`
	RuntimeConfiguration    string                          `protobuf:"bytes,10,opt,name=RuntimeConfiguration,proto3" json:"RuntimeConfiguration,omitempty"`
	Elements                map[string]*ElementSetupMessage `protobuf:"bytes,11,rep,name=Elements,proto3" json:"Elements,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral    struct{}                        `json:"-"`
	XXX_unrecognized        []byte                          `json:"-"`
	XXX_sizecache           int32                           `json:"-"`
}

func (m *SetupMessage) Reset()         { *m = SetupMessage{} }
func (m *SetupMessage) String() string { return proto.CompactTextString(m) }
func (*SetupMessage) ProtoMessage()    {}
func (*SetupMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_304cfb64bcde0875, []int{5}
}

func (m *SetupMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetupMessage.Unmarshal(m, b)
}
func (m *SetupMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetupMessage.Marshal(b, m, deterministic)
}
func (m *SetupMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetupMessage.Merge(m, src)
}
func (m *SetupMessage) XXX_Size() int {
	return xxx_messageInfo_SetupMessage.Size(m)
}
func (m *SetupMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SetupMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SetupMessage proto.InternalMessageInfo

func (m *SetupMessage) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *SetupMessage) GetSolution() string {
	if m != nil {
		return m.Solution
	}
	return ""
}

func (m *SetupMessage) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *SetupMessage) GetElement() string {
	if m != nil {
		return m.Element
	}
	return ""
}

func (m *SetupMessage) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *SetupMessage) GetInstance() string {
	if m != nil {
		return m.Instance
	}
	return ""
}

func (m *SetupMessage) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *SetupMessage) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *SetupMessage) GetDesignTimeConfiguration() string {
	if m != nil {
		return m.DesignTimeConfiguration
	}
	return ""
}

func (m *SetupMessage) GetRuntimeConfiguration() string {
	if m != nil {
		return m.RuntimeConfiguration
	}
	return ""
}

func (m *SetupMessage) GetElements() map[string]*ElementSetupMessage {
	if m != nil {
		return m.Elements
	}
	return nil
}

type StatusMessage struct {
	Domain               string   `protobuf:"bytes,1,opt,name=Domain,proto3" json:"Domain,omitempty"`
	Solution             string   `protobuf:"bytes,2,opt,name=Solution,proto3" json:"Solution,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=Version,proto3" json:"Version,omitempty"`
	Element              string   `protobuf:"bytes,4,opt,name=Element,proto3" json:"Element,omitempty"`
	ElementEndpoint      string   `protobuf:"bytes,5,opt,name=ElementEndpoint,proto3" json:"ElementEndpoint,omitempty"`
	Cluster              string   `protobuf:"bytes,6,opt,name=Cluster,proto3" json:"Cluster,omitempty"`
	ClusterEndpoint      string   `protobuf:"bytes,7,opt,name=ClusterEndpoint,proto3" json:"ClusterEndpoint,omitempty"`
	ClusterState         string   `protobuf:"bytes,8,opt,name=ClusterState,proto3" json:"ClusterState,omitempty"`
	Instance             string   `protobuf:"bytes,9,opt,name=Instance,proto3" json:"Instance,omitempty"`
	InstanceEndpoint     string   `protobuf:"bytes,10,opt,name=InstanceEndpoint,proto3" json:"InstanceEndpoint,omitempty"`
	InstanceState        string   `protobuf:"bytes,11,opt,name=InstanceState,proto3" json:"InstanceState,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusMessage) Reset()         { *m = StatusMessage{} }
func (m *StatusMessage) String() string { return proto.CompactTextString(m) }
func (*StatusMessage) ProtoMessage()    {}
func (*StatusMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_304cfb64bcde0875, []int{6}
}

func (m *StatusMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusMessage.Unmarshal(m, b)
}
func (m *StatusMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusMessage.Marshal(b, m, deterministic)
}
func (m *StatusMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusMessage.Merge(m, src)
}
func (m *StatusMessage) XXX_Size() int {
	return xxx_messageInfo_StatusMessage.Size(m)
}
func (m *StatusMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StatusMessage proto.InternalMessageInfo

func (m *StatusMessage) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *StatusMessage) GetSolution() string {
	if m != nil {
		return m.Solution
	}
	return ""
}

func (m *StatusMessage) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *StatusMessage) GetElement() string {
	if m != nil {
		return m.Element
	}
	return ""
}

func (m *StatusMessage) GetElementEndpoint() string {
	if m != nil {
		return m.ElementEndpoint
	}
	return ""
}

func (m *StatusMessage) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *StatusMessage) GetClusterEndpoint() string {
	if m != nil {
		return m.ClusterEndpoint
	}
	return ""
}

func (m *StatusMessage) GetClusterState() string {
	if m != nil {
		return m.ClusterState
	}
	return ""
}

func (m *StatusMessage) GetInstance() string {
	if m != nil {
		return m.Instance
	}
	return ""
}

func (m *StatusMessage) GetInstanceEndpoint() string {
	if m != nil {
		return m.InstanceEndpoint
	}
	return ""
}

func (m *StatusMessage) GetInstanceState() string {
	if m != nil {
		return m.InstanceState
	}
	return ""
}

func init() {
	proto.RegisterType((*VoidMessage)(nil), "tsai.eu.VoidMessage")
	proto.RegisterType((*InstanceSetupMessage)(nil), "tsai.eu.InstanceSetupMessage")
	proto.RegisterType((*RelationshipSetupMessage)(nil), "tsai.eu.RelationshipSetupMessage")
	proto.RegisterType((*ClusterSetupMessage)(nil), "tsai.eu.ClusterSetupMessage")
	proto.RegisterMapType((map[string]*InstanceSetupMessage)(nil), "tsai.eu.ClusterSetupMessage.InstancesEntry")
	proto.RegisterMapType((map[string]*RelationshipSetupMessage)(nil), "tsai.eu.ClusterSetupMessage.RelationshipsEntry")
	proto.RegisterType((*ElementSetupMessage)(nil), "tsai.eu.ElementSetupMessage")
	proto.RegisterMapType((map[string]*ClusterSetupMessage)(nil), "tsai.eu.ElementSetupMessage.ClustersEntry")
	proto.RegisterType((*SetupMessage)(nil), "tsai.eu.SetupMessage")
	proto.RegisterMapType((map[string]*ElementSetupMessage)(nil), "tsai.eu.SetupMessage.ElementsEntry")
	proto.RegisterType((*StatusMessage)(nil), "tsai.eu.StatusMessage")
}

func init() {
	proto.RegisterFile("tsai.eu/solar/controller/solar.proto", fileDescriptor_304cfb64bcde0875)
}

var fileDescriptor_304cfb64bcde0875 = []byte{
	// 831 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0xc1, 0x6e, 0xdb, 0x38,
	0x10, 0x8d, 0x2d, 0x4b, 0xb2, 0xc7, 0xf1, 0x26, 0xcb, 0x78, 0xb3, 0x82, 0x91, 0x05, 0xb2, 0xde,
	0x00, 0x6b, 0x64, 0x17, 0x0e, 0xe0, 0x60, 0x11, 0x27, 0x58, 0xb4, 0x40, 0x9c, 0x14, 0xc8, 0x21,
	0x17, 0x39, 0x0d, 0xd0, 0xf6, 0xa4, 0x3a, 0xac, 0x23, 0x44, 0x96, 0x0c, 0x91, 0x2a, 0x92, 0x7e,
	0x49, 0x8f, 0x3d, 0xf6, 0xda, 0xbf, 0xe9, 0x07, 0xf4, 0x1f, 0x7a, 0x2d, 0x44, 0x91, 0x32, 0x29,
	0xcb, 0x6e, 0xac, 0x43, 0xd1, 0x1b, 0xe7, 0x91, 0x43, 0x9a, 0xef, 0xbd, 0x19, 0xca, 0xb0, 0x47,
	0x89, 0xe3, 0x76, 0x71, 0x74, 0x40, 0x02, 0xcf, 0x09, 0x0f, 0x46, 0x81, 0x4f, 0xc3, 0xc0, 0xf3,
	0x70, 0x98, 0x00, 0xdd, 0x69, 0x18, 0xd0, 0x00, 0x99, 0x7c, 0x55, 0xfb, 0x6f, 0xa8, 0x5f, 0x07,
	0xee, 0xcd, 0x25, 0x26, 0xc4, 0x19, 0x63, 0x64, 0x81, 0x79, 0x8d, 0x43, 0xe2, 0x06, 0xbe, 0x55,
	0xda, 0x2d, 0x75, 0x6a, 0xb6, 0x08, 0xdb, 0xef, 0xcb, 0xd0, 0xbc, 0xf0, 0x09, 0x75, 0xfc, 0x11,
	0x1e, 0x62, 0x1a, 0x4d, 0x45, 0x4a, 0x0b, 0xaa, 0x02, 0xe7, 0x39, 0x69, 0x8c, 0xb6, 0xc1, 0xb8,
	0x72, 0xc2, 0x31, 0xa6, 0x56, 0x99, 0xcd, 0xf0, 0x08, 0x35, 0x41, 0x1f, 0x52, 0x87, 0x62, 0x4b,
	0x63, 0x70, 0x12, 0xa0, 0x7f, 0xe1, 0xd7, 0x53, 0x87, 0xe0, 0x41, 0xe0, 0xbf, 0x71, 0xc7, 0x51,
	0xe8, 0xd0, 0xf8, 0x67, 0x54, 0xd8, 0x8a, 0xf9, 0x09, 0xd4, 0x87, 0xdf, 0xcf, 0x30, 0x71, 0xc7,
	0xfe, 0x95, 0x3b, 0xc9, 0xe4, 0xe8, 0x2c, 0x67, 0xd1, 0x34, 0xea, 0x41, 0xd3, 0x8e, 0x7c, 0x3a,
	0x97, 0x66, 0xb0, 0xb4, 0xdc, 0xb9, 0xf8, 0x96, 0xe7, 0xfe, 0xcd, 0x34, 0x70, 0x7d, 0x6a, 0x99,
	0xc9, 0x2d, 0x45, 0xdc, 0xfe, 0x5c, 0x06, 0xcb, 0xc6, 0x1e, 0x5b, 0x48, 0x6e, 0xdd, 0xa9, 0x42,
	0x4f, 0x1b, 0xd6, 0xe5, 0x39, 0x4e, 0x91, 0x82, 0xc5, 0xac, 0x9f, 0x7b, 0x78, 0x82, 0x7d, 0xc1,
	0x93, 0x08, 0x65, 0x3d, 0x34, 0x45, 0x0f, 0x89, 0xda, 0x4a, 0x3e, 0xb5, 0xfa, 0x77, 0xa9, 0x35,
	0x0a, 0x50, 0x6b, 0x16, 0xa3, 0xb6, 0xfa, 0x48, 0x6a, 0x6b, 0x19, 0x6a, 0x3f, 0xe9, 0xb0, 0x35,
	0xf0, 0x22, 0x42, 0x71, 0xa8, 0xb0, 0x6a, 0x81, 0xc9, 0x61, 0xe1, 0x53, 0x1e, 0xae, 0x68, 0xb9,
	0x4d, 0xd0, 0x2e, 0xdd, 0xc4, 0x64, 0x9a, 0x1d, 0x0f, 0x19, 0xe2, 0xdc, 0x33, 0xf6, 0x62, 0xc4,
	0xb9, 0x47, 0x08, 0x2a, 0x43, 0xf7, 0x1d, 0x66, 0x74, 0x69, 0x36, 0x1b, 0xe7, 0xf3, 0x69, 0x16,
	0xe0, 0xb3, 0x5a, 0x8c, 0xcf, 0xda, 0x23, 0xf9, 0x04, 0x95, 0x4f, 0xf4, 0x1c, 0x1a, 0xb2, 0xf3,
	0x88, 0x55, 0xdf, 0xd5, 0x3a, 0xf5, 0xde, 0x41, 0x97, 0xf7, 0x83, 0x6e, 0x0e, 0xd9, 0x5d, 0x25,
	0xe3, 0xdc, 0xa7, 0xe1, 0x83, 0xad, 0xee, 0x82, 0x2e, 0xa0, 0x26, 0x6a, 0x9e, 0x58, 0xeb, 0x6c,
	0xcb, 0x7f, 0x96, 0x6e, 0x99, 0xae, 0x4e, 0xb6, 0x9b, 0x65, 0xb7, 0x46, 0x80, 0xe6, 0xcf, 0x8b,
	0x55, 0xb9, 0xc3, 0x0f, 0x5c, 0xeb, 0x78, 0x88, 0x8e, 0x40, 0x7f, 0xeb, 0x78, 0x11, 0x66, 0x32,
	0xd7, 0x7b, 0x7f, 0xa6, 0xc7, 0x2d, 0xaa, 0x44, 0x3b, 0x59, 0x7f, 0x52, 0xee, 0x97, 0x5a, 0xaf,
	0xe0, 0x17, 0xf5, 0x17, 0xe4, 0x1c, 0x70, 0xa8, 0x1e, 0xf0, 0x47, 0x7a, 0x40, 0x5e, 0x17, 0x94,
	0x36, 0x6f, 0x7f, 0xd4, 0x60, 0x8b, 0xd7, 0x6f, 0xd6, 0xb3, 0xa2, 0xca, 0x4b, 0x6a, 0x95, 0xef,
	0x40, 0x6d, 0x10, 0x4c, 0xa6, 0x81, 0x3f, 0xeb, 0x00, 0x33, 0x40, 0x72, 0xb4, 0x96, 0xef, 0xe8,
	0x8a, 0xec, 0xe8, 0x9f, 0xa6, 0x2d, 0xa2, 0x67, 0x50, 0xe5, 0xd2, 0x13, 0xab, 0xca, 0x3c, 0xb1,
	0x9f, 0x72, 0x98, 0xc3, 0x8f, 0xf0, 0x09, 0xb7, 0x44, 0x9a, 0xdb, 0x7a, 0x01, 0x0d, 0x65, 0x2a,
	0x47, 0xab, 0x9e, 0xaa, 0xd5, 0xce, 0x32, 0xef, 0xc9, 0x52, 0x7d, 0xd1, 0x60, 0x5d, 0xd1, 0x68,
	0x1b, 0x8c, 0xb3, 0x60, 0xe2, 0xb8, 0xe2, 0xf9, 0xe3, 0x51, 0x7c, 0xcf, 0x61, 0xe0, 0x45, 0x8c,
	0x8f, 0x44, 0xa0, 0x34, 0x5e, 0xd2, 0xa3, 0x25, 0xc5, 0x2b, 0x73, 0x7d, 0x5d, 0xf4, 0x2f, 0x5d,
	0xed, 0x5f, 0xf2, 0x73, 0x6a, 0x2c, 0x7c, 0x4e, 0xcd, 0x7c, 0x27, 0x54, 0x1f, 0xe9, 0x84, 0x5a,
	0x31, 0x27, 0xc0, 0x12, 0x27, 0x3c, 0x85, 0x2a, 0xbf, 0x9c, 0x68, 0x2a, 0x7f, 0xa5, 0x2a, 0x28,
	0x32, 0x8b, 0x55, 0x5c, 0x66, 0x11, 0xc6, 0x32, 0x2b, 0x53, 0xab, 0xc8, 0x9c, 0x63, 0x27, 0x59,
	0xe6, 0xaf, 0x65, 0x68, 0xc4, 0x9c, 0x44, 0xe4, 0x47, 0xeb, 0xdc, 0x81, 0x0d, 0x3e, 0x4c, 0xcb,
	0x24, 0xd1, 0x3b, 0x0b, 0xcb, 0x8e, 0x30, 0x54, 0x47, 0x74, 0x60, 0x83, 0x0f, 0x33, 0xa5, 0x96,
	0x85, 0xe3, 0x6f, 0x0d, 0x61, 0x78, 0xc9, 0x0e, 0x0a, 0xa6, 0xf8, 0xab, 0x96, 0xf1, 0xd7, 0x3e,
	0x6c, 0x8a, 0x71, 0xe6, 0x05, 0x99, 0xc3, 0xd1, 0x1e, 0x34, 0xd2, 0x46, 0xc8, 0x0e, 0xab, 0xb3,
	0x85, 0x2a, 0xd8, 0xfb, 0x50, 0x01, 0x18, 0xa4, 0x9f, 0xa0, 0xe8, 0x3f, 0xd0, 0x07, 0xb7, 0x78,
	0x74, 0x87, 0x9a, 0xa9, 0x74, 0xd2, 0xd7, 0x67, 0x2b, 0x17, 0x6d, 0xaf, 0xa1, 0x63, 0x30, 0x06,
	0x21, 0x8e, 0x7f, 0xfd, 0x6f, 0xb9, 0x9e, 0x6a, 0x6d, 0xcf, 0x60, 0x59, 0xe6, 0xf6, 0x1a, 0x3a,
	0x01, 0xf3, 0x0c, 0x13, 0x1a, 0x06, 0x0f, 0xab, 0xe7, 0xf6, 0x59, 0x59, 0x85, 0x74, 0xf5, 0xcc,
	0x23, 0xa8, 0x0c, 0x69, 0x30, 0x5d, 0x3d, 0xf1, 0xff, 0xf8, 0x25, 0x48, 0xca, 0xaa, 0xc0, 0x65,
	0x9f, 0x40, 0xdd, 0xc6, 0xa3, 0xe2, 0xf9, 0x7d, 0xd0, 0x6d, 0x4c, 0x70, 0x81, 0x0b, 0x1f, 0x83,
	0x91, 0x40, 0x2b, 0xa7, 0x9e, 0xb6, 0x5e, 0x5a, 0x8b, 0xfe, 0xb2, 0xbc, 0x36, 0xd8, 0xbf, 0x95,
	0xc3, 0x6f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x44, 0x7a, 0x20, 0x3c, 0xd5, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ControllerClient is the client API for Controller service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ControllerClient interface {
	Check(ctx context.Context, in *VoidMessage, opts ...grpc.CallOption) (*VoidMessage, error)
	Create(ctx context.Context, in *SetupMessage, opts ...grpc.CallOption) (*StatusMessage, error)
	Destroy(ctx context.Context, in *SetupMessage, opts ...grpc.CallOption) (*StatusMessage, error)
	Start(ctx context.Context, in *SetupMessage, opts ...grpc.CallOption) (*StatusMessage, error)
	Stop(ctx context.Context, in *SetupMessage, opts ...grpc.CallOption) (*StatusMessage, error)
	Configure(ctx context.Context, in *SetupMessage, opts ...grpc.CallOption) (*StatusMessage, error)
	Reconfigure(ctx context.Context, in *SetupMessage, opts ...grpc.CallOption) (*StatusMessage, error)
	Reset(ctx context.Context, in *SetupMessage, opts ...grpc.CallOption) (*StatusMessage, error)
	Status(ctx context.Context, in *SetupMessage, opts ...grpc.CallOption) (*StatusMessage, error)
}

type controllerClient struct {
	cc *grpc.ClientConn
}

func NewControllerClient(cc *grpc.ClientConn) ControllerClient {
	return &controllerClient{cc}
}

func (c *controllerClient) Check(ctx context.Context, in *VoidMessage, opts ...grpc.CallOption) (*VoidMessage, error) {
	out := new(VoidMessage)
	err := c.cc.Invoke(ctx, "/tsai.eu.Controller/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) Create(ctx context.Context, in *SetupMessage, opts ...grpc.CallOption) (*StatusMessage, error) {
	out := new(StatusMessage)
	err := c.cc.Invoke(ctx, "/tsai.eu.Controller/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) Destroy(ctx context.Context, in *SetupMessage, opts ...grpc.CallOption) (*StatusMessage, error) {
	out := new(StatusMessage)
	err := c.cc.Invoke(ctx, "/tsai.eu.Controller/Destroy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) Start(ctx context.Context, in *SetupMessage, opts ...grpc.CallOption) (*StatusMessage, error) {
	out := new(StatusMessage)
	err := c.cc.Invoke(ctx, "/tsai.eu.Controller/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) Stop(ctx context.Context, in *SetupMessage, opts ...grpc.CallOption) (*StatusMessage, error) {
	out := new(StatusMessage)
	err := c.cc.Invoke(ctx, "/tsai.eu.Controller/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) Configure(ctx context.Context, in *SetupMessage, opts ...grpc.CallOption) (*StatusMessage, error) {
	out := new(StatusMessage)
	err := c.cc.Invoke(ctx, "/tsai.eu.Controller/Configure", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) Reconfigure(ctx context.Context, in *SetupMessage, opts ...grpc.CallOption) (*StatusMessage, error) {
	out := new(StatusMessage)
	err := c.cc.Invoke(ctx, "/tsai.eu.Controller/Reconfigure", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) Reset(ctx context.Context, in *SetupMessage, opts ...grpc.CallOption) (*StatusMessage, error) {
	out := new(StatusMessage)
	err := c.cc.Invoke(ctx, "/tsai.eu.Controller/Reset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) Status(ctx context.Context, in *SetupMessage, opts ...grpc.CallOption) (*StatusMessage, error) {
	out := new(StatusMessage)
	err := c.cc.Invoke(ctx, "/tsai.eu.Controller/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerServer is the server API for Controller service.
type ControllerServer interface {
	Check(context.Context, *VoidMessage) (*VoidMessage, error)
	Create(context.Context, *SetupMessage) (*StatusMessage, error)
	Destroy(context.Context, *SetupMessage) (*StatusMessage, error)
	Start(context.Context, *SetupMessage) (*StatusMessage, error)
	Stop(context.Context, *SetupMessage) (*StatusMessage, error)
	Configure(context.Context, *SetupMessage) (*StatusMessage, error)
	Reconfigure(context.Context, *SetupMessage) (*StatusMessage, error)
	Reset(context.Context, *SetupMessage) (*StatusMessage, error)
	Status(context.Context, *SetupMessage) (*StatusMessage, error)
}

// UnimplementedControllerServer can be embedded to have forward compatible implementations.
type UnimplementedControllerServer struct {
}

func (*UnimplementedControllerServer) Check(ctx context.Context, req *VoidMessage) (*VoidMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (*UnimplementedControllerServer) Create(ctx context.Context, req *SetupMessage) (*StatusMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedControllerServer) Destroy(ctx context.Context, req *SetupMessage) (*StatusMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Destroy not implemented")
}
func (*UnimplementedControllerServer) Start(ctx context.Context, req *SetupMessage) (*StatusMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (*UnimplementedControllerServer) Stop(ctx context.Context, req *SetupMessage) (*StatusMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (*UnimplementedControllerServer) Configure(ctx context.Context, req *SetupMessage) (*StatusMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Configure not implemented")
}
func (*UnimplementedControllerServer) Reconfigure(ctx context.Context, req *SetupMessage) (*StatusMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reconfigure not implemented")
}
func (*UnimplementedControllerServer) Reset(ctx context.Context, req *SetupMessage) (*StatusMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reset not implemented")
}
func (*UnimplementedControllerServer) Status(ctx context.Context, req *SetupMessage) (*StatusMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}

func RegisterControllerServer(s *grpc.Server, srv ControllerServer) {
	s.RegisterService(&_Controller_serviceDesc, srv)
}

func _Controller_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoidMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tsai.eu.Controller/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).Check(ctx, req.(*VoidMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tsai.eu.Controller/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).Create(ctx, req.(*SetupMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_Destroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).Destroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tsai.eu.Controller/Destroy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).Destroy(ctx, req.(*SetupMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tsai.eu.Controller/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).Start(ctx, req.(*SetupMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tsai.eu.Controller/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).Stop(ctx, req.(*SetupMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tsai.eu.Controller/Configure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).Configure(ctx, req.(*SetupMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_Reconfigure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).Reconfigure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tsai.eu.Controller/Reconfigure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).Reconfigure(ctx, req.(*SetupMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tsai.eu.Controller/Reset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).Reset(ctx, req.(*SetupMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tsai.eu.Controller/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).Status(ctx, req.(*SetupMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Controller_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tsai.eu.Controller",
	HandlerType: (*ControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _Controller_Check_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Controller_Create_Handler,
		},
		{
			MethodName: "Destroy",
			Handler:    _Controller_Destroy_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _Controller_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Controller_Stop_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _Controller_Configure_Handler,
		},
		{
			MethodName: "Reconfigure",
			Handler:    _Controller_Reconfigure_Handler,
		},
		{
			MethodName: "Reset",
			Handler:    _Controller_Reset_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Controller_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tsai.eu/solar/controller/solar.proto",
}
